# Generated by Django 2.2.5 on 2020-11-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0003_questions_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='category',
            field=models.CharField(choices=[('hostels', 'Hostels'), ('academics', 'Academics')], default=0, max_length=20),
        ),
    ]
