# Generated by Django 2.2.5 on 2020-11-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0004_auto_20201113_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='askquestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('hostels', 'Hostels'), ('academics', 'Academics')], default=0, max_length=20)),
                ('question', models.CharField(max_length=200)),
            ],
        ),
    ]
